import sqlite3
conn=sqlite3.connect('geeks.db')
cursor=conn.cursor()
cursor.execute('create table bus(bus_id varchar(5) not null primary key,bus_type varchar(10),capacity int,fair int,op_id varchar(5) not null,route_id varchar(5) not null,foreign key(op_id) references operator(opr_id),foreign key(route_id) references route(r_id))')
cursor.execute('create table operator(opr_id varchar(5) primary key,name varchar(20),address varchar(50),phone char(10),email varchar(30))')
cursor.execute('create table running(b_id varchar(5) ,run_date date,seat_avail int,foreign key(b_id) references bus(bus_id))')
cursor.execute('create table route(r_id varchar(5) not null primary key,s_name varchar(20),s_id varchar(5),e_name varchar(20),e_id varchar(5) )')
cursor.execute('create table booking_history(name varchar(20),gender char(1),no_of_seat int,phone char(10),age int,booking_ref varchar(10) not null primary key,booking_date date,travel_date date,bid varchar(5),foreign key(bid) references bus(bus_id))')
cursor.execute('''INSERT INTO bus VALUES('1','AC 2x2',50,350,'2','1')''')
cursor.execute('''INSERT INTO bus VALUES('2','ac 2x2',50,350,'2','2')''')
cursor.execute('''INSERT INTO bus VALUES('3','3x2',80,250,'1','1')''')
cursor.execute('''INSERT INTO bus VALUES('4','ac 3x2',60,400,'3','2')''')
cursor.execute('''INSERT INTO bus VALUES('5','2x2',50,350,'3','4')''')
cursor.execute('''INSERT INTO bus VALUES('6','2x2',50,300,'1','3')''')
cursor.execute('''INSERT INTO operator VALUES('1','satluj travels','satluj travels office, near bus stand, guna','9756432165','busbooking@satlujtravels.in')''')
cursor.execute('''INSERT INTO operator VALUES('2','gangotri travels','near jaypee college','7654329845','gangred@char.in')''')
cursor.execute('''INSERT INTO operator VALUES('3','himadri travels','near raghogarh,guna','6754329867','himadri@charedbus.in')''')
cursor.execute('''INSERT INTO running VALUES('1','2022-12-01',50)''')
cursor.execute('''INSERT INTO running VALUES('1','2022-12-02',50)''')
cursor.execute('''INSERT INTO running VALUES('1','2022-12-03',50)''')
cursor.execute('''INSERT INTO running VALUES('1','2022-12-04',50)''')
cursor.execute('''INSERT INTO running VALUES('2','2022-12-05',41)''')
cursor.execute('''INSERT INTO running VALUES('2','2022-12-06',47)''')
cursor.execute('''INSERT INTO running VALUES('2','2022-12-07',50)''')
cursor.execute('''INSERT INTO running VALUES('2','2022-12-01',50)''')
cursor.execute('''INSERT INTO running VALUES('3','2022-12-02',77)''')
cursor.execute('''INSERT INTO running VALUES('3','2022-12-03',80)''')
cursor.execute('''INSERT INTO running VALUES('4','2022-12-04',56)''')
cursor.execute('''INSERT INTO running VALUES('4','2022-12-05',60)''')
cursor.execute('''INSERT INTO running VALUES('5','2022-12-06',50)''')
cursor.execute('''INSERT INTO running VALUES('6','2022-12-07',50)''')
cursor.execute(''' INSERT INTO route VALUES('1','guna','080','bihar','066')''')
cursor.execute(''' INSERT INTO route VALUES('2','bihar','066','guna','080')''')
cursor.execute(''' INSERT INTO route VALUES('3','guna','080','gorakhpur','003')''')
cursor.execute(''' INSERT INTO route VALUES('4','gorakhpur','003','guna','080')''')
cursor.execute(''' INSERT INTO route VALUES('5','guna','066','lucknow','003')''')
cursor.execute(''' INSERT INTO route VALUES('6','lucknow','003','guna','066')''')
conn.commit()
conn.close()
